name: Code Coverage

on:
  workflow_run:
    workflows: ["PostgreSQL Docker Container"]
    branches:
      - main
      - master
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Archive Jacoco reports
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-reports
        path: java/target/site/jacoco
