name: Code Coverage

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Archive Jacoco reports
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-reports
        path: java/target/site/jacoco
