name: Start PostgreSQL Docker Container

on: [push]

jobs:
  postgresql:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Wait for PostgreSQL to start
        run: dockerize -wait tcp://localhost:5432 -timeout 1m

