name: PostgreSQL Docker Container

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run PostgreSQL container
      run: |
        docker build -t my-postgres-image -f Dockerfile .
        docker run -d --name my-postgres-container -p 5432:5432 my-postgres-image
    - name: Wait for PostgreSQL to start
      run: docker exec my-postgres-container sh -c "while ! pg_isready -h localhost; do sleep 1; done"

    - name: Run tests or other tasks
      run: |
        # Add your tests or other tasks here that use the PostgreSQL container.
        # For example:
        # - psql -h localhost -U myuser -d mydatabase -c "SELECT 1;"
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.5
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        
    - name: Test the Java part
      run: | 
        cd ./java
        mvn compile
        # Uncomment the next line to execute a select * in order to show the result set in the log
        # mvn exec:java -Dexec.mainClass="it.unibz.githubactions.Main"
        mvn test
